####
# Multi-stage native image build (Mandrel 25 / Quarkus container build)
####
FROM quay.io/quarkus/ubi9-quarkus-mandrel-builder-image:jdk-25 AS build
COPY --chown=quarkus:quarkus . /code
USER quarkus
WORKDIR /code
RUN ./gradlew build -Dquarkus.native.enabled=true -Dquarkus.native.container-build=false -x test

FROM quay.io/quarkus/ubi9-quarkus-micro-image:2.0
WORKDIR /work/
COPY --from=build /code/build/*-runner /work/application
RUN chmod 775 /work /work/application
EXPOSE 8080
USER 1001
CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]
